services:
  redis:
    image: redis:7-alpine
    container_name: orderinv-redis
    ports:
      - "6380:6379"

  app:
    build:
      context: ./orderinventory
    container_name: orderinv-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orderinv-db.c1q08uqci4f7.ap-south-1.rds.amazonaws.com:5432/orderinv
      SPRING_DATASOURCE_USERNAME: orderinv_user
      SPRING_DATASOURCE_PASSWORD: Bhj83kdo
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

