spring.application.name=orderinventory
spring.datasource.url=jdbc:postgresql://localhost:5433/orderinv
spring.datasource.username=orderinv_user
spring.datasource.password=orderinv_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=localhost
spring.data.redis.port=6380
